- name: Deploy Docker container with docker-compose
  hosts: roulette
  remote_user: root
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: aalysher/roulette:latest
        source: pull

    - name: Stop and remove existing container (if any)
      docker_container:
        name: roulette
        state: absent

    - name: Ensure roulette directory exists
      file:
        path: /root/roulette
        state: directory
        recurse: yes

    - name: Copy docker-compose.yml to the server
      copy:
        src: docker-compose.yml
        dest: /root/roulette/docker-compose.yml

    - name: Start the Docker container with docker-compose
      command: docker compose -f /root/roulette/docker-compose.yml up -d

